name: Monitor de Vendas 1900min
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar Codigo
        uses: actions/checkout@v3
        
      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Instalar Bibliotecas
        run: pip install requests
        
      - name: Executar Bot
        env:
          # AQUI ESTA A CORRECAO: Passando todas as chaves
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }} 
        run: python bot_email.py
