name: Monitor de Vendas 1900min
on:
  schedule:
    - cron: '*/5 * * * *' # Comando para rodar a cada 5 minutos
  workflow_dispatch: # Permite que você clique em um botão para testar agora

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Instalar Dependencias
        run: pip install requests
      - name: Executar Bot
        run: python bot_email.py
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
